[[inputs.mqtt_consumer]]
  servers = ["tcp://jouw-mqtt-broker:1883"]
  topics = ["quatt/+/telemetry"] # De + is de gehashte MAC-ID van de gebruiker
  data_format = "json"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "$INFLUX_TOKEN"
  organization = "quatt_community"
  bucket = "heatpump_data"
